---
- name: Create a very simple VM in GCP
  hosts: localhost
  gather_facts: no
  tasks:
    - name: create a disk
      google.cloud.gcp_compute_disk:
        name: "{{item.name}}"
        size_gb: "{{item.size}}"
        source_image: projects/debian-cloud/global/images/debian-12-bookworm-v20241112
        zone: us-central1-a
        project: "terraform-426822"
        state: present
      with_items: "{{vm_list}}"
      register: disk
    - name: Save  disk
      set_stats:
        data:
          disk: "{{item.disk}}"
