- name: Create GCP VM with Existing Disk
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
   - name: Create VM Instance
     gcp_compute_instance:
       name: "{{name}}"
       machine_type: "n1-standard-1"
       zone: "us-central1-a"
       network_interfaces:
       - network:  "{{network}}"
       disks:
       - auto_delete: 'false'
         boot: 'true'
         source: "{{disk}}" 
      #  auth_kind: serviceaccount
      #  service_account_file: "terraform-426822-5b3f85703c63.json"
       project: "terraform-426822"
       state: "{{statuss}}"
############################################## edited

   - name: Retrieve details of the specific VM in GCP
     google.cloud.gcp_compute_instance_info:
       project: "terraform-426822"
       zone: "us-central1-a"
       filters:
       - name = "{{name}}"
  #     auth_kind: serviceaccount 
  #      service_account_file: Downloads/terraform-426822-5b3f85703c63.json
     register: vm_details

   - name: nnsd 
     set_fact:
       ip: "{{vm_details.resources[0].networkInterfaces[0].networkIP}}"
       size: "{{vm_details.resources[0].disks[0].diskSizeGb}}"
       os: "{{vm_details.resources[0].disks[0].licenses}}"

   - name: fff
     debug: 
       msg: ip "{{ip}}" and disk size "{{size}}" and os "{{os}}"

   - name: save artifacts
     set_stats:
       data:
         vm_name: "{{name}}"
         ip: "{{ip}}"
         size: "{{size}}"
         os: "{{os}}"


