---
- name: Send email via Gmail SMTP
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Save the count of the array in a variable
    set_fact:
      array_count: "{{ vm_list | length }}" 
  - name: success stats
    set_stats: 
      data: 
        "{{create_instance_response.results[item].item.name}}": "{{create_instance_response.results[item].content}}"
    when: create_instance_response.results[item].failed == false
    loop: "{{ range(0, array_count | int ) | list }}"
   
  - name: failed stats
    set_stats: 
      data: 
        "{{create_instance_response.results[item].item.name}}": "{{create_instance_response.results[item].json.error.errors[0].reason}}"
    when: create_instance_response.results[item].failed
    loop: "{{ range(0, array_count | int ) | list }}"



  - name: Send email through Gmail SMTP
    community.general.mail:
      host: "smtp.mailersend.net"
      port: 587
      username: "MS_DMiwdK@trial-jpzkmgqr3rv4059v.mlsender.net"
      password: "ulqHQPkF8ANYOCa1"  # Use Ansible Vault for security!
      to: "basemitdept@gmail.com"
      subject: "Test Email from Ansible"
     # body: "This is a test email sent via Gmail SMTP using Ansible."
      from: "MS_DMiwdK@trial-jpzkmgqr3rv4059v.mlsender.net"
      secure: starttls
      subtype: html
      body: |
        
        "{{test3}}"